/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.*;


public class App {

    public static void main(String[] args) {
        StandardCalculator calc =new StandardCalculator();
        Scanner input=new Scanner(System.in);
        boolean exit=false;

        while(!exit){
       try{
        System.out.println("Select the following option: ");
        System.out.println("1. for Addition");
        System.out.println("2. for Subtraction");
        System.out.println("3. for Multiplication");
        System.out.println("4. for Division");
        System.out.println("0. for Exit");

        int selected = input.nextInt();
        switch (selected){
            case 1:
            System.out.println("You have Selected: Addition");
            break;
            case 2:
            System.out.println("You have Selected: Subtraction");
            break;
            case 3:
            System.out.println("You have Selected: Multiplication");
            break;
            case 4:
            System.out.println("You have Selected: Division");
            break;
            case 0:
            System.out.println("You have Selected: Exit");
            exit=true;
            continue;
            default:
            System.out.println("Kindly input correct response");
            input.nextLine();
            continue;
        }
        System.out.println("Enter first number: ");
        Double num1 = input.nextDouble();
        System.out.println("Enter Second number: ");
        Double num2=input.nextDouble();

        switch (selected) {
            case 1:
                calc.add(num1, num2);
                System.out.println("Addition is: " + calc.printResult());
                break;
            case 2:
                calc.subtract(num1, num2);
                System.out.println("Subtraction is: " + calc.printResult());
                break;
            case 3:
                calc.multiply(num1, num2);
                System.out.println("Multiplication is: " + calc.printResult());
                break;
            case 4:
                calc.divide(num1, num2);
                System.out.println("Division is: " + calc.printResult());
                break;
        }

        }catch(Exception e){
            System.out.println("Invalid number: Pleaser enter valid number: ");
            input.nextLine();
        }
        
        }
       
    input.close();

}
}
