/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        StandardCalculator calc =new StandardCalculator();

        calc.add(23,51);
        System.out.println(calc.printResult());
        calc.add(Double.MAX_VALUE,1);
        System.out.println(calc.printResult());
        calc.multiply(3, 4);
        System.out.println(calc.printResult());
    }

    
}
